builds:
  - id: "shoes-lxd-multi-shoes-provider"
    dir: shoes-lxd-multi
    binary: shoes-lxd-multi
    env:
      - CGO_ENABLED=0
  - id: "shoes-lxd-multi-serevr"
    dir: server
    binary: shoes-lxd-multi-server
    env:
      - CGO_ENABLED=0
  - id: "shoes-lxd-multi-pool-agent"
    dir: pool-agent
    binary: shoes-lxd-multi-pool-agent
    env:
      - CGO_ENABLED=0
archives:
  - format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
