name: Test
on:
  push:
    branches:
      - "**"
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - server
          - shoes-lxd-multi
          - pool-agent
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version-file: ${{ matrix.target }}/go.mod
      - name: lint
        run: |
          GO111MODULE=off GOBIN=$(pwd)/bin go get golang.org/x/lint/golint
          bin/golint -set_exit_status ./...
      - name: go vet
        run: |
          cd ${{ matrix.target }}
          go vet ./...
      - name: go test
        run: |
          cd ${{ matrix.target }}
          go test ./...
  docker-build-test:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3
       with:
         fetch-depth: 1
     - name: docker build
       run: |
         cd server
         docker build .
